apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus # fixed uid so provisioned dashboards can reference it
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
