import fp from 'fastify-plugin';

/**
 * Echoes the request id back as `x-request-id` so clients can correlate a
 * response with server logs/traces. The id itself is generated by Fastify
 * (genReqId in app.ts) or taken from an inbound `x-request-id` header.
 */
export const correlationIdPlugin = fp((app) => {
  // Callback (done) style is the unambiguous sync onSend form: a sync hook that
  // merely *returns* a value can leave Fastify waiting → use done(null, payload).
  app.addHook('onSend', (request, reply, payload, done) => {
    reply.header('x-request-id', request.id);
    done(null, payload);
  });
});
